### ISSUE TITLE
Error with GamePointsAPI

### ISSUE THREAD

**Issue by Probableinsane** [Klemms/SlotMachineIssues#21]
[00:41:25 ERROR]: Could not pass event PlayerInteractEvent to SlotMachine v6.5.0
java.lang.NoClassDefFoundError: su/nightexpress/gamepoints/GamePointsAPI
        at fr.klemms.slotmachine.placeholders.VariableGamePoints.getVariable(VariableGamePoints.java:15) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.klemms.slotmachine.placeholders.Variables.replaceVariable(Variables.java:38) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.klemms.slotmachine.placeholders.Variables.getFormattedStrings(Variables.java:47) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.klemms.slotmachine.layouts.CSGOLayout.generateLever(CSGOLayout.java:74) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.klemms.slotmachine.layouts.CSGOLayout.init(CSGOLayout.java:66) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.minuskube.inv.SmartInventory.open(SmartInventory.java:52) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.minuskube.inv.SmartInventory.open(SmartInventory.java:35) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.klemms.slotmachine.SlotMachine.openMachine(SlotMachine.java:275) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.klemms.slotmachine.MachineMethods.openmachine(MachineMethods.java:53) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at fr.klemms.slotmachine.events.PluginListener.onPlayerInteract(PluginListener.java:373) ~[slotmachine-6.5.0-SPIGOTLIVE.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor871.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:540) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1820) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-52]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: su.nightexpress.gamepoints.GamePointsAPI
        ... 34 more

**Comment by Klemms** [comment]
Fixed in 6.5.1
