### ISSUE TITLE
SSL Certificate problem

### ISSUE THREAD

**Issue by griffindeed** [Klemms/SlotMachineIssues#27]
Started having a problem with the slot machine plugin a few days ago. I thought it might be the last update 6.5.9, so I downgraded to see if it was that, however I'm still getting the same errors.
I've disabled the update checker to stop it. Looks like it might be "https://minecraft.klemms.ovh" and not the plugin.
The error:
`[08Jul2022 03:39:02.283] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[08Jul2022 03:39:02.284] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[08Jul2022 03:39:02.284] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
[08Jul2022 03:39:02.284] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:295)
[08Jul2022 03:39:02.284] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:290)
[08Jul2022 03:39:02.284] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356)
[08Jul2022 03:39:02.285] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231)
[08Jul2022 03:39:02.285] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174)
[08Jul2022 03:39:02.285] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
[08Jul2022 03:39:02.285] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
[08Jul2022 03:39:02.285] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
[08Jul2022 03:39:02.285] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
[08Jul2022 03:39:02.285] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1359)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1268)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[08Jul2022 03:39:02.286] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/java.net.URL.openStream(URL.java:1140)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at fr.klemms.slotmachine.libs.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at fr.klemms.slotmachine.KlemmsUpdate$1.run(KlemmsUpdate.java:76)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08Jul2022 03:39:02.287] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08Jul2022 03:39:02.288] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [fr.klemms.slotmachine.KlemmsUpdate$1:run:102]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[08Jul2022 03:39:02.288] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[08Jul2022 03:39:02.288] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
[08Jul2022 03:39:02.288] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263)
[08Jul2022 03:39:02.288] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[08Jul2022 03:39:02.288] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
[08Jul2022 03:39:02.288] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1340)
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: 	... 24 more
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: Caused by: java.security.cert.CertPathValidatorException: validity check failed
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:237)
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:145)
[08Jul2022 03:39:02.289] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:84)
[08Jul2022 03:39:02.290] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
[08Jul2022 03:39:02.290] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
[08Jul2022 03:39:02.290] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	... 30 more
[08Jul2022 03:39:02.290] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed Jul 06 21:36:50 UTC 2022
[08Jul2022 03:39:02.290] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
[08Jul2022 03:39:02.290] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:683)
[08Jul2022 03:39:02.291] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
[08Jul2022 03:39:02.291] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
[08Jul2022 03:39:02.291] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
[08Jul2022 03:39:02.291] [Craft Scheduler Thread - 6/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	... 35 more`

**Comment by JJBirdgender** [comment]
I'm also having this error, seems harmless but a bit annoying

**Comment by Klemms** [comment]
This should be solved now, thanks for the report
