### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProtoGhost** [Klemms/SlotMachineIssues#28]
[07:00:45 INFO]: [BanItem] Successfully loaded 16 blacklisted & 0 whitelisted item(s).
[07:00:45 WARN]: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[07:00:45 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[07:00:45 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
[07:00:45 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
[07:00:45 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
[07:00:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
[07:00:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
[07:00:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
[07:00:45 WARN]:        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[07:00:45 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[07:00:45 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[07:00:45 WARN]:        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
[07:00:45 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[07:00:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[07:00:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[07:00:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[07:00:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[07:00:45 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[07:00:45 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[07:00:45 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[07:00:45 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[07:00:45 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[07:00:45 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
[07:00:45 WARN]:        at slotmachine-6.5.9-SPIGOT.jar//fr.klemms.slotmachine.libs.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
[07:00:45 WARN]:        at slotmachine-6.5.9-SPIGOT.jar//fr.klemms.slotmachine.KlemmsUpdate$1.run(KlemmsUpdate.java:76)
[07:00:45 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[07:00:45 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:00:45 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:00:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:00:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:00:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:00:45 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[07:00:45 WARN]:        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
[07:00:45 WARN]:        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263)
[07:00:45 WARN]:        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[07:00:45 WARN]:        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[07:00:45 WARN]:        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[07:00:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
[07:00:45 WARN]:        ... 25 more
[07:00:45 WARN]: Caused by: java.security.cert.CertPathValidatorException: validity check failed
[07:00:45 WARN]:        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[07:00:45 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
[07:00:45 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
[07:00:45 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
[07:00:45 WARN]:        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
[07:00:45 WARN]:        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
[07:00:45 WARN]:        ... 30 more
[07:00:45 WARN]: Caused by: java.security.cert.CertificateExpiredException: NotAfter: Mon Sep 05 23:50:03 CEST 2022
[07:00:45 WARN]:        at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
[07:00:45 WARN]:        at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:619)
[07:00:45 WARN]:        at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
[07:00:45 WARN]:        at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
[07:00:45 WARN]:        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
[07:00:45 WARN]:        ... 35 more

**Comment by Klemms** [comment]
This issue should be resolved
