### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by GothkittyGirl** [Klemms/SlotMachineIssues#3]
```
[Sat, 10. Aug 2019 02:40:53 EDT WARN] java.net.ConnectException: Connection timed out (Connection timed out)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.net.PlainSocketImpl.socketConnect(Native Method)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.net.Socket.connect(Socket.java:589)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.net.URL.openStream(URL.java:1045)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at fr.klemms.slotmachine.apache.org.apache.commons.io.IOUtils.toString(IOUtils.java:1198)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at fr.klemms.slotmachine.KlemmsUpdate$1.run(KlemmsUpdate.java:66)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Sat, 10. Aug 2019 02:40:53 EDT WARN]     at java.lang.Thread.run(Thread.java:748)
```

**Comment by Klemms** [comment]
Hey, this issue should be solved
