### ISSUE TITLE
console warnings

### ISSUE THREAD

**Issue by Floodo** [Klemms/SlotMachineIssues#31]
Hi, every time I start server, it writes this warning message at the beginning, and then every 30 minutes. Can you help me? Thanks :) 

Paper 1.19

[21:25:20 WARN]: java.net.ConnectException: Connection timed out: connect
[21:25:20 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[21:25:20 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[21:25:20 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[21:25:20 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[21:25:20 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:25:20 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[21:25:20 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[21:25:20 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[21:25:20 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[21:25:20 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
[21:25:20 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[21:25:20 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[21:25:20 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
[21:25:20 WARN]:        at slotmachine-6.5.9-SPIGOT.jar//fr.klemms.slotmachine.libs.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
[21:25:20 WARN]:        at slotmachine-6.5.9-SPIGOT.jar//fr.klemms.slotmachine.KlemmsUpdate$1.run(KlemmsUpdate.java:76)
[21:25:20 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:25:20 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:25:20 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:25:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:25:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:25:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by flashpaul** [comment]
same warning

**Comment by Klemms** [comment]
I dis some changes, does it work now ?
If not then it seems like it would be a dns update issue

**Comment by Floodo** [comment]
The last error  for me was at 16:32....since then no error :) ...if it will continue, i will reopen this issue.....Thanks! :)

**Comment by Klemms** [comment]
The next error should probably be at 17:32

**Comment by Floodo** [comment]
I had it every 30 minutes, but no prob, i will wait

**Comment by Floodo** [comment]
no errors :) Thank you
