### ISSUE TITLE
Oraxen support

### ISSUE THREAD

**Issue by dcsepy01** [Klemms/SlotMachineIssues#36]
```
[07:41:00 INFO]: [SlotMachine] Loading file c94623ff-c883-4a8a-9f68-dbf3b63192ce.yml
[07:41:00 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getBlockAt(int, int, int)" because the return value of "org.bukkit.Bukkit.getWorld(java.util.UUID)" is null
[07:41:00 WARN]:        at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.SlotMachineBlock.getBlock(SlotMachineBlock.java:99)
[07:41:00 WARN]:        at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.SlotMachineBlock.addSlotMachineBlock(SlotMachineBlock.java:27)
[07:41:00 WARN]:        at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.Config.loadMachines(Config.java:464)
[07:41:00 WARN]:        at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.SlotPlugin.onEnable(SlotPlugin.java:120)
[07:41:00 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:41:00 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:41:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[07:41:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[07:41:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[07:41:00 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[07:41:00 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[07:41:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[07:41:00 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[07:41:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[07:41:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:41:00 ERROR]: [SlotMachine] An exception was caught when loading c94623ff-c883-4a8a-9f68-dbf3b63192ce.yml
```

I think plugin is loading before Oraxen, and the location is empty.. Please fix it :D 
(if i use plugman to reload, then works :D)

Server version: 1.18.2 Purpur
Java 17

**Comment by Klemms** [comment]
Hi, I'll see what I can do, in the meantime if you wan oraxen to load first, edit the plugin.yml in the SlotMachine.jar (you can open it with winrar or 7zip) and add the plugin to the softdepend line, you can find the name you should put in the plugin.yml of Oraxen

**Comment by dcsepy01** [comment]
Hi, no, still error message :/

**Comment by Klemms** [comment]
It's weird because it says it can't find the world your block is in, could you try creating another machine in that world, then open the file for this world and copy the "worldUID" value to the machine that has an issue, it should solve it, what's weird is that world UIDs should never change

**Comment by dcsepy01** [comment]
Sorry for late response :) if i try with normal block (not placed by oraxen) works.

**Comment by Klemms** [comment]
I've tried some things but ultimately decided that I won't add support at least for now. Oraxen is a paid plugin and it's impossible for me to correctly support this without having it and I'm not paying 20€ especially since my plugin is free.

You can try asking Oraxen for support, I looked around a bit and there is no reason for this to not work if Oraxen correctly fires a PlayerInteractEntityEvent (entity) or PlayerInteractEvent (block). There seems to be some issues on their github regarding events though.
