### ISSUE TITLE
Warn on start up

### ISSUE THREAD

**Issue by Floodo** [Klemms/SlotMachineIssues#40]
Hello :), I just start up my server (after it suddenly crashed) and than every start I have this warn. Paper 1.19
 
[14:39:34 WARN]: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[14:39:34 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[14:39:34 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
[14:39:34 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
[14:39:34 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
[14:39:34 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
[14:39:34 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
[14:39:34 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
[14:39:34 WARN]:        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[14:39:34 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[14:39:34 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[14:39:34 WARN]:        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
[14:39:34 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[14:39:34 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
[14:39:34 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
[14:39:34 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[14:39:34 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[14:39:34 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[14:39:34 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[14:39:34 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[14:39:34 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[14:39:34 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[14:39:34 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
[14:39:34 WARN]:        at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.libs.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
[14:39:34 WARN]:        at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.KlemmsUpdate$1.run(KlemmsUpdate.java:76)
[14:39:34 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:39:34 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:39:34 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:39:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:39:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:39:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:39:34 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[14:39:34 WARN]:        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
[14:39:34 WARN]:        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263)
[14:39:34 WARN]:        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[14:39:34 WARN]:        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[14:39:34 WARN]:        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[14:39:34 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
[14:39:34 WARN]:        ... 25 more
[14:39:34 WARN]: Caused by: java.security.cert.CertPathValidatorException: validity check failed
[14:39:34 WARN]:        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[14:39:34 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
[14:39:34 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
[14:39:34 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
[14:39:34 WARN]:        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
[14:39:34 WARN]:        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
[14:39:34 WARN]:        ... 30 more
[14:39:34 WARN]: Caused by: java.security.cert.CertificateExpiredException: NotAfter: Thu Sep 14 10:29:57 CEST 2023
[14:39:34 WARN]:        at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
[14:39:34 WARN]:        at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:619)
[14:39:34 WARN]:        at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
[14:39:34 WARN]:        at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
[14:39:34 WARN]:        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
[14:39:34 WARN]:        ... 35 more

**Comment by Klemms** [comment]
This issue should be resolved now
